version: '3.1'

services:

  mongo:
    image: mongo:4.4
    container_name: insta-mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./mongo_etc:/etc/mongo/
      - mongo1_data:/data/db
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  mongosetup:
    container_name: mongo-setup
    depends_on:
      mongo:
        condition: service_started
        required: true
    entrypoint:
      - bash
      - -c
      - 'sleep 10 && mongo --host 10.5.0.5 --port 27017 --eval "rs.initiate()"'
    image: mongo:4.4
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    restart: "no"

  insta-bot:
    container_name: insta-bot
    build: .
    depends_on:
     - mongo
    restart: always
    ports:
      - 6060:6060
    env_file:
      - .env
    volumes:
      - ./src/:/app/src
      - ./.env:/app/.env
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1
volumes:
  mongo1_data:
